#!/usr/bin/env bash

#Add npm to path
#export PATH="$HOME/.npm-packages/bin:$PATH"
#export PATH="/usr/local/opt/node@10/bin:~/.rbenv/shims:$PATH"
#export PATH="/usr/local/opt/node@12/bin:~/.rbenv/shims:$PATH"
export HOMEBREW_PREFIX="/opt/homebrew";
export HOMEBREW_CELLAR="/opt/homebrew/Cellar";
export HOMEBREW_REPOSITORY="/opt/homebrew";
export PATH="/opt/homebrew/bin:/opt/homebrew/sbin${PATH+:$PATH}";
export MANPATH="/opt/homebrew/share/man${MANPATH+:$MANPATH}:";
export INFOPATH="/opt/homebrew/share/info:${INFOPATH:-}";
